site_name: EN ↔ ET andmevaldkonna sõnastik
site_description: Avalik EN ↔ ET andmevaldkonna mõistete sõnastik
site_url: https://kristor.github.io/andmed-et-en/
repo_name: KristoR/andmed-et-en
repo_url: https://github.com/KristoR/andmed-et-en

theme:
  name: material
  language: et
  features:
    - content.tabs.link
    - navigation.tabs

plugins:
  - search

markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences

nav:
  - Sõnastik: index.md
  - Panustamine: contributing.md
